# Gradle
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Parchment
parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

# Minecraft / NeoForge
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.233
loader_version_range=[1,)

# Mod
mod_id=mago_compat
mod_name=Mago Compatibility
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=kr.mago.compat

# Iron's Spells 'n Spellbooks
irons_spells_version=1.21.1-3.16.1
irons_lib_version=1.21.1-1.1.0

# JEI
jei_version=19.27.0.336
